print("\N{grinning face}", "\N{grinning face}", "\N{grinning face}")
print("Вітаю вас в моєму розважальному чат боті!", "\N{grinning face}")
print("Як тебе звати?")
name = input("Введіть ваше ім'я \n")
print("Привіт", name)
print("Вибери розділ який тебе цікавить")
